export const SET_LOADING = 'SET_LOADING';
export const SET_DONATION = 'SET_DONATION';
export const SET_SUCCESS_DONATION = 'SET_SUCCESS_DONATION';
export const SET_ERROR_DONATION = 'SET_ERROR_DONATION';